Task2
PeregudovSergey/TP pull request #3
Opened 2022-03-12 20:22 UTC by PeregudovSergey

Здравсвуйте! 

Не нашел как нормально привязать гугл тесты, те когда я вызываю 
add_executable(CTest ${MAIN_TEST} ${TEST}) 
то ему же нужно понять, что запсукается гугл тест(хотя я тоже не понимаю почему, ведь внутри написан их инклуд, ему почему-то нужно еще дописывать какие-то флаги). поэтому я запускал и инклудил библиотеки, которых не хватает 
target_link_libraries(CTest ${GTEST_LIBRARIES})
target_link_libraries(CTest gmock gtest pthread)
если честно, то я ничего не понял

а еще когда мы линкуем MyLib. main же с MyLib оперирует как с машинным кодом, те он как-то умеет обращаться к уже собранной библиотеке(а в libMyLib.so уже нолики единички)?

я дописал target_include_directories(CTest PUBLIC ${PROJECT_SOURCE_DIR}) потому что иначе не работал бы #include "A/index.h". Но что он делает в этом случае? Он говорит, что мы в нашу зону видимости для этого таргета добавляем эту папку(или собираем этот таргет в этой папке)? Вдруг у нас была бы ситуация сложнее, те мы инклудили какие-то разные библиотеки и те лежали в разных относительных путях. Как тогда быть в этой ситуации или инклуд этих двух библиотек(A/index.h, B/lib.h) уже что-то не очень правильное? 

Простите, что так много вопросов. 
Спасибо!

2022-03-14 00:43 UTC, VTroyanGolovyan requested changes
Я не очень понял вопросы. Можешь пожалуйста получше сформулировать?

Что значит "запустить и заинклюдить библиотеку?"

2022-03-14 00:43 UTC, VTroyanGolovyan commented on task2/CMakeLists.txt
> +target_link_libraries(CTest gmock gtest pthread)
зачем gmock?

2022-04-03 21:32 UTC, PeregudovSergey commented on task2/CMakeLists.txt
> +target_link_libraries(CTest gmock gtest pthread)
я с теми вопросами вроде разобрался, спасибо.
а без гмока почему-то не работает, какую-то боьшую ошибку выводит(вот часть)

/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x28): undefined reference to `pthread_getspecific'
/usr/bin/ld: gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x3d): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libgtest.a(gtest-all.cc.o): in function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x28): undefined reference to `pthread_getspecific'
/usr/bin/ld: gtest-all.cc:

2022-05-06 09:24 UTC, VTroyanGolovyan commented
Принято)

2022-05-06 09:26 UTC, VTroyanGolovyan approved these changes

2023-04-16 20:45 UTC, merged